ALTER TABLE cart
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE product 
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE users
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;